--  Drop and Create BL_CL Table for Local Sales (Cleansed Data)
CREATE TABLE IF NOT EXISTS BL_CL.CLEAN_LOCAL_SALES (
    ORDER_SRC_ID INT PRIMARY KEY,
    ORDER_DT DATE NOT NULL DEFAULT CURRENT_DATE,
    LOCATION TEXT DEFAULT 'N/A',
    STATE TEXT DEFAULT 'N/A',
    PRODUCT_SRC_ID INT NOT NULL DEFAULT 0,
    PRODUCT_CATEGORY TEXT DEFAULT 'N/A',
    SUPPLIER_NAME TEXT DEFAULT 'N/A',
    SUPPLIER_COUNTRY TEXT DEFAULT 'N/A',
    SUPPLIER_RATING DECIMAL(2,1) DEFAULT 0.0,
    BUYER_SRC_ID INT NOT NULL DEFAULT 0,
    BRANCH_SRC_ID INT NOT NULL DEFAULT 0,
    SALES_PRICE DECIMAL(10,2) DEFAULT 0.00,
    REVENUE DECIMAL(10,2) DEFAULT 0.00,
    PRODUCT_COST DECIMAL(10,2) DEFAULT 0.00,
    PROFIT DECIMAL(10,2) DEFAULT 0.00,
    SOURCE_SYSTEM TEXT NOT NULL DEFAULT 'SRC',
    SOURCE_ENTITY TEXT NOT NULL DEFAULT 'LOCAL',
    INSERT_DT TIMESTAMP DEFAULT NOW()
);

--  Drop and Create BL_CL Table for Global Sales (Cleansed Data)
CREATE TABLE IF NOT EXISTS BL_CL.CLEAN_GLOBAL_SALES (
    ORDER_SRC_ID INT PRIMARY KEY,
    ORDER_DT DATE NOT NULL DEFAULT CURRENT_DATE,
    COUNTRY TEXT DEFAULT 'N/A',
    CITY TEXT DEFAULT 'N/A',
    PRODUCT_SRC_ID INT NOT NULL DEFAULT 0,
    PRODUCT_CATEGORY TEXT DEFAULT 'N/A',
    SUPPLIER_NAME TEXT DEFAULT 'N/A',
    SUPPLIER_COUNTRY TEXT DEFAULT 'N/A',
    SUPPLIER_RATING DECIMAL(2,1) DEFAULT 0.0,
    BUYER_SRC_ID INT NOT NULL DEFAULT 0,
    BRANCH_SRC_ID INT NOT NULL DEFAULT 0,
    SALES_PRICE DECIMAL(10,2) DEFAULT 0.00,
    REVENUE DECIMAL(10,2) DEFAULT 0.00,
    PRODUCT_COST DECIMAL(10,2) DEFAULT 0.00,
    PROFIT DECIMAL(10,2) DEFAULT 0.00,
    SHIPPING_TYPE TEXT DEFAULT 'N/A',
    SHIPPING_COST DECIMAL(10,2) DEFAULT 0.00,
    SOURCE_SYSTEM TEXT NOT NULL DEFAULT 'SRC',
    SOURCE_ENTITY TEXT NOT NULL DEFAULT 'GLOBAL',
    INSERT_DT TIMESTAMP DEFAULT NOW()
);

-- Create Log Table for Tracking Last Order Date
DROP TABLE IF EXISTS BL_LOG.CLEAN_LOAD_LOG;
CREATE TABLE IF NOT EXISTS BL_LOG.CLEAN_LOAD_LOG (
    table_name TEXT PRIMARY KEY,
    last_order_date DATE DEFAULT '1900-01-01',
    inserted_rows INT DEFAULT 0,
    status TEXT DEFAULT 'SUCCESS',
    error_message TEXT DEFAULT NULL
);

--  Ensure Log Table Has inserted_rows Column
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'clean_load_log' 
        AND column_name = 'inserted_rows'
    ) THEN
        ALTER TABLE BL_LOG.CLEAN_LOAD_LOG ADD COLUMN inserted_rows INT DEFAULT 0;
    END IF;
END $$;

-- Ensure Log Table has an Initial Entry
INSERT INTO BL_LOG.CLEAN_LOAD_LOG (table_name, last_order_date, inserted_rows, status)
VALUES 
    ('BL_CL.CLEAN_LOCAL_SALES', '1900-01-01', 0, 'PENDING'),
    ('BL_CL.CLEAN_GLOBAL_SALES', '1900-01-01', 0, 'PENDING')
ON CONFLICT (table_name) DO NOTHING; -- Prevent duplicate inserts
